repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: (doc/ReleaseNotes.md)
  - repo: local
    hooks:
      - id: readme-links-check
        name: README links check
        entry: python3 ./scripts/updateReadmeLinks.py --check
        files: (^README.md$)
        language: system
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.6'
    hooks:
      - id: clang-format
        types: [c++]
        exclude: (edm4hep/(edm4hep|src)/.*(h|cc)$|EDM4HEPVersion.h)
