name: key4hep_linux

on: [push, pull_request]

jobs:
  build-and-test-key4hep:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["sw.hsf.org/key4hep",
                  "sw-nightlies.hsf.org/key4hep"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: aidasoft/run-lcg-view@v3
      with:
        container: centos7
        view-path: /cvmfs/${{ matrix.release }}
        run: |
          mkdir build install
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_INSTALL_PREFIX=../install \
            -G Ninja
          ninja -k0
          ctest --output-on-failure
          ninja install
          cd -
          echo "Test downstream usage"
          export CMAKE_PREFIX_PATH=$PWD/install:$CMAKE_PREFIX_PATH
          cd test/downstream-project-cmake-test
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_INSTALL_PREFIX=../install \
            -G Ninja
          ninja -k0
