name: lcg_linux_with_podio

on: [push, pull_request]

jobs:
  build-and-test-with-podio:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["dev3/x86_64-el9-clang16-opt",
              "dev4/x86_64-el9-clang16-opt",
              "dev4/x86_64-el9-gcc13-opt",
              "LCG_106/x86_64-el9-gcc13-opt"]
        CXX_STANDARD: [20]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: AIDASoft/podio
        path: podio
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - uses: aidasoft/run-lcg-view@v4
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          STARTDIR=$(pwd)
          echo "::group::Build podio"
          cd podio
          echo "Building podio @"$(git log -1 --format=%H)
          mkdir build install
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STANDARD }} \
            -DENABLE_SIO=ON \
            -DENABLE_RNTUPLE=ON \
            -DENABLE_DATASOURCE=ON \
            -DBUILD_TESTING=OFF \
            -DCMAKE_INSTALL_PREFIX=$(pwd)/../install \
            -G Ninja
          ninja -k0 install
          cd ..
          source init.sh && env.sh
          echo "::endgroup::"
          echo "::group::Build edm4hep"
          cd $STARTDIR
          echo "Building edm4hep"
          mkdir build install
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STANDARD }} \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DUSE_EXTERNAL_CATCH2=OFF \
            -G Ninja
          ninja -k0
          ctest --output-on-failure
          ninja install
          cd -
          echo "::endgroup::"
          echo "::group::Test downstream usage"
          export CMAKE_PREFIX_PATH=$PWD/install:$CMAKE_PREFIX_PATH
          cd test/downstream-project-cmake-test
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_STANDARD=${{ matrix.CXX_STANDARD }} \
            -DCMAKE_INSTALL_PREFIX=../install \
            -G Ninja
          ninja -k0
          echo "::endgroup::"
